/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    AdminSession: () => import('#controllers/admin/admin_session_controller'),
    AppVersions: () => import('#controllers/admin/app_versions_controller'),
  },
  api: {
    AppVersionsApi: () => import('#controllers/api/app_versions_api_controller'),
    CatalogApi: () => import('#controllers/api/catalog_api_controller'),
    FavoritesApi: () => import('#controllers/api/favorites_api_controller'),
    RoomsApi: () => import('#controllers/api/rooms_api_controller'),
    StreamsApi: () => import('#controllers/api/streams_api_controller'),
    SubtitlesApi: () => import('#controllers/api/subtitles_api_controller'),
    TopcinemaApi: () => import('#controllers/api/topcinema_api_controller'),
    TvApi: () => import('#controllers/api/tv_api_controller'),
  },
  LiveTv: () => import('#controllers/live_tv_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Rooms: () => import('#controllers/rooms_controller'),
  Session: () => import('#controllers/session_controller'),
  Videos: () => import('#controllers/videos_controller'),
}
