/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    RoomsApi: () => import('#controllers/api/rooms_api_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  Rooms: () => import('#controllers/rooms_controller'),
  Session: () => import('#controllers/session_controller'),
  Videos: () => import('#controllers/videos_controller'),
}
