/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class RoomSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'externalUrl', 'id', 'isUserCreated', 'magnet', 'name', 'passwordHash', 'reactions', 'roomType', 'slug', 'subtitleFilename', 'thumbnailFilename', 'videoFilename', 'viewCount'] as const
  $columns = RoomSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUserCreated: boolean
  @column()
  declare magnet: string | null
  @column()
  declare name: string
  @column()
  declare passwordHash: string | null
  @column()
  declare reactions: string | null
  @column()
  declare roomType: string
  @column()
  declare slug: string
  @column()
  declare subtitleFilename: string | null
  @column()
  declare thumbnailFilename: string
  @column()
  declare videoFilename: string
  @column()
  declare viewCount: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdminSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = AdminSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'fileName', 'fileSize', 'id', 'isMandatory', 'packageName', 'releaseNotes', 'status', 'updatedAt', 'versionCode', 'versionName'] as const
  $columns = AppVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare fileSize: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isMandatory: boolean
  @column()
  declare packageName: string
  @column()
  declare releaseNotes: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare versionCode: number
  @column()
  declare versionName: string
}
