/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class RoomSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'externalUrl', 'id', 'isUserCreated', 'name', 'passwordHash', 'reactions', 'roomType', 'slug', 'subtitleFilename', 'thumbnailFilename', 'videoFilename', 'viewCount'] as const
  $columns = RoomSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUserCreated: boolean
  @column()
  declare name: string
  @column()
  declare passwordHash: string | null
  @column()
  declare reactions: string | null
  @column()
  declare roomType: string
  @column()
  declare slug: string
  @column()
  declare subtitleFilename: string | null
  @column()
  declare thumbnailFilename: string
  @column()
  declare videoFilename: string
  @column()
  declare viewCount: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
